### ISSUE TITLE
Error "All MyHome gateways are already configured" while installing myHome Integration in HA

### ISSUE THREAD

**Issue by edilhouse** [anotherjulien/MyHOME#42]
Hi

I've installed myHome via HACS and while trying to install the integration I get the error
`All MyHome gateways are already configured`

My gateway is MH200 and I'm actually using a node-red node to manage it, but I would like to integrate it in HA and dismiss the nide-red one.

Any suggestion on how to solve ?

Thanks

**Comment by anotherjulien** [comment]
I don't really know how the node-red integration shows the gateway in Home Assistant, is it showing as a device?
If so it might be that they use the MAC address as a unique ID (which is recommended by Home Assistant), that means that my integration would not be able to register a new device with the same unique ID.

**Comment by jeroen-vankelecom** [comment]
Maybe this resolves your problem as well... when you install the integration, `find_gateways` is called (automatic gateway discovery by the OWNd package). If this call returns an empty list, you will end up with the abort message you are seeing. 

https://github.com/anotherjulien/MyHOME/blob/master/custom_components/myhome/config_flow.py#L102-L117
```
        local_gateways = [
            gateway
            for gateway in local_gateways
            if gateway["serialNumber"] not in already_configured
        ]

        if not local_gateways:
            return self.async_abort(reason="all_configured")
```

If you just comment the if-block, the process can go through and you will end up with a User wizard that requests you to configure a custom gateway (by providing the IP/Mac/etc ourself).

@anotherjulien I think it is better to allow the user to define a custom gateway in this case, instead of bailing out...

**Comment by xenix13** [comment]
Hello sorry for my bad English but I also have this problem I migrated my docker home assistant instance to another machine and I have this message that appeared. I did the procedure you give I have the possibility to create a custom gateway but after entering the information I have an error : "Unknown error occurred"

I use F454 gateway.

Should have any idea ?

Thanks.

**Comment by robgiom** [comment]
Hi @anotherjulien 

I have the same issue today. Unfortunately I needed to reconfigured HA application and once I've download all the configuration via HACS I received the message reported "All MyHome gateways are already configured"
Do you have an idea of the reason why it is occured?

Many thanks in advance

**Comment by anotherjulien** [comment]
Could you try with the current master version?
I followed Jeroen's advice and it should allow you to create a custom gateway.

**Comment by robgiom** [comment]
> Could you try with the current master version? I followed Jeroen's advice and it should allow you to create a custom gateway.

Hi @anotherjulien 
I tried again but when I fill the info I received the follow error

![image](https://user-images.githubusercontent.com/93553187/178786219-3a0cc638-b4dc-4564-8dce-2942277035e7.png)

Did I make something wrong?

Many thanks

**Comment by bubez81** [comment]
same error here it's because of the new control+home from netatmo switch?

**Comment by robgiom** [comment]
I don't have netatmo switch but Myhomeserver1 gateway of Bticino. But still the same!

**Comment by bubez81** [comment]
no sorry, I meant the switch to the new firmware of MyHomeserver1 and the switch to the netatmo application

**Comment by anotherjulien** [comment]
Any other logs?
I suppose you're sure about the IP address and that it's reachable from your HA instance?

**Comment by robgiom** [comment]
Hi @anotherjulien 

here is the log

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: aiohttp.server
Source: custom_components/myhome/config_flow.py:156 
Integration: MyHome (documentation, issues) 
First occurred: 20:06:45 (2 occurrences) 
Last logged: 20:41:58

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/myhome/config_flow.py", line 156, in async_step_custom
    user_input["serialNumber"] = device_registry.format_mac(
NameError: name 'device_registry' is not defined

do you have an idea of the issue occured?

mant thanks in advance

**Comment by anotherjulien** [comment]
Yup, I see what's wrong...
I've published a fix to the master version just now, if you want to try.

**Comment by robgiom** [comment]
Hi @anotherjulien 
unfortunately still the same

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: aiohttp.server
Source: custom_components/myhome/config_flow.py:272
Integration: MyHome (documentation, issues)
First occurred: 21:08:53 (3 occurrences)
Last logged: 21:14:26

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/myhome/config_flow.py", line 175, in async_step_custom
    return await self.async_step_test_connection()
  File "/config/custom_components/myhome/config_flow.py", line 272, in async_step_test_connection
    test_result = await test_session.test_connection()
  File "/usr/local/lib/python3.10/site-packages/OWNd/connection.py", line 227, in test_connection
    ) = await asyncio.open_connection(
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.178.158', 20000)


The strange thing is that on the last winter I have set properly the configuration. Do you have a copy of the old configuration?

Sorry to bother you but maybe this can help other users

**Comment by robgiom** [comment]
Hi @anotherjulien 
now it works properly

Great!

**Comment by bubez81** [comment]
Yes! Thank you
